export const freedie = [
    {
        id:'Daniel-Panjwaneey',
        name:'Daniel Panjwaneey',
        imgSrc:'./dan.jpg',
        desc:"Daniel Arthur Panjwaneey is a seasoned music producer, media professional, and audio engineer from Karachi, Pakistan, with an illustrious career spanning over 15 years. He began his journey in the music industry professionally in 2007, quickly establishing himself as a creative force in audio production and engineering.\n\nFrom 2010 to 2014, Daniel was part of the globally acclaimed Coke Studio (Pakistan) during seasons 4, 5, and 6, where he contributed as an assistant audio engineer. His expertise further flourished as the Chief Audio Engineer at A for Aleph from 2016 to 2021.\n\nIn 2021, Daniel founded Cape Monze Records, an independent label that reflects his passion for discovering and nurturing talent. Throughout his career, Daniel has been involved in over 400+ song productions, excelling in roles as an artist, producer, audio engineer, and mastering engineer. His technical prowess and creative vision continue to shape the sonic landscapes of contemporary music.\n\nConnect with Daniel to bring your next audiobook or musical project to life!",
        role:'Producer/Curator/Audio-Engineer',
        eMail:'danielpanjwaneey@gmail.com',
        fb:'https://www.facebook.com/danielpanjwaneey',
        insta:'https://www.instagram.com/alienpandajury.kukido/',
        x:'',
        linkedIn:'https://www.facebook.com/danielpanjwaneey',
        spotify:'https://open.spotify.com/artist/6OfjFTS57bjf89tHhKTLgi?si=HNGhtYN7RquxjUp7c1nSpg',
        linktree:'https://linktr.ee/alienpandajury',
        youtube:'https://www.youtube.com/playlist?list=PL5Ryp-hMdvtHIGjgXtZCY4cLDkHhdSPNf',
        soundcloud:'https://soundcloud.com/alienpandajury',
        bandcamp:'https://alienpandajury.bandcamp.com/',
        github:'',
        behance:'',
        dribble:'',
        portfolio:'https://linktr.ee/alienpandajury',
        cv:'https://drive.google.com/file/d/1ayIulWLwX40-B4yvE05D572kW17nMxWH/view?usp=sharing',
        shout:''
    },
    {
        id:'Saqlain-Haider',
        name:'Saqlain Haider',
        imgSrc:'./saqlain.jpg',
        desc:"Saqlain is a front-end-focused full-stack creative developer whose work has won an international award; he has also been nominated for another. He brings a deep passion for art, music, and mycology into his development process, crafting truly immersive and high-performance websites. \n\nAs both a musician and a serious mycologist, he sees patterns, structures, and interactions in unique ways—this translates into code that is both elegantly structured and deeply interconnected. Every component he builds complements the whole, ensuring seamless user experiences.\n\nHis aim is to craft digital experiences that are visually stunning, technically superior, and built to global award-winning standards. If you're looking for a site that stands out and performs exceptionally, get in touch with Saqlain and make something extraordinary together.",
        role:'Software-Engineer/ Web-developer',
        eMail:'saqlainhaider77@gmail.com',
        fb:'https://www.facebook.com/saqlainh3/',
        insta:'https://www.instagram.com/svqlvin_dp_hvider/',
        x:'https://www.instagram.com/svqlvin_dp_hvider/',
        linkedIn:'https://www.linkedin.com/in/saqlainhaider77/',
        spotify:'',
        linktree:'',
        youtube:'',
        soundcloud:'',
        bandcamp:'',
        github:'https://github.com/Saqman77',
        behance:'https://www.behance.net/saqlainhaider77',
        dribble:'https://dribbble.com/saqlain_haider?onboarding=true&designer=true ',
        portfolio:'https://www.linkedin.com/in/saqlainhaider77?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app',
        cv:'https://docs.google.com/document/d/1Z15r6VH9_M_oTBcu0B6lj_p9_iRMT1BQkuUpAe_JGnM/edit?usp=sharing',
        shout:'A shout out to Saqlain. Thank you for developing this whimsically fun-tastic website for us. Your coding skills are genius-level.'
    },
    {
        id:'Amna-Ali',
        name:'Amna Ali',
        imgSrc:'./Amna-Ali.jpeg',
        desc:"Amna Ali is a freelance graphic designer with a passion for creating visually striking designs that tell a story. She specializes in logo design, branding, and digital illustrations, combining creativity and technical expertise to bring ideas to life. Through close collaboration with clients, she strives to understand their vision and craft designs that truly resonate with their audience.\n\nOver the years, Amna has had the privilege of working with businesses from various industries to build memorable visual identities. When not designing, she dedicates time to exploring the latest design trends and honing her skills to stay inspired and ahead of the curve.",
        role:'Illustrator',
        eMail:'aamna9318@gmail.com',
        fb:'',
        insta:'',
        x:'',
        linkedIn:'',
        spotify:'',
        linktree:'',
        youtube:'',
        soundcloud:'',
        bandcamp:'',
        github:'',
        behance:'',
        dribble:'',
        portfolio:'https://www.behance.net/amnaali51',
        cv:'',
        shout:'A shout out to Amna. Thank you for making the amazing graphics used on our website. If we created a comic book, this is how we’d draw our characters.'
    },
    {
        id:'Beenish-Sarfaraz',
        name:'Beenish Sarfaraz',
        imgSrc:'./been.jpg',
        desc:"Beenish Sarfaraz is a visual artist and educator based in Karachi, Pakistan. Her interest lies in cultural and heritage stories, environment and social-engaged art making. Currently, she is a faculty member at Beaconhouse National University.\n\nPreviously, she has worked on projects with Coke Studio (2018), Geo TV Network, Centre of Arts-based Methodologies and Wellbeing, British Council, State Bank Museum-Pakistan, Manchester Museum, ShirkatGah and DAWN. She uses inquiry and play as her method of research.",
        role:'Graphic Designer/Creative Nonfiction Writer ',
        eMail:'beenish.s.ali@gmail.com',
        // phone:'+92-0900-78601',
        fb:'',
        insta:'',
        x:'',
        linkedIn:'',
        spotify:'',
        linktree:'',
        youtube:'',
        soundcloud:'',
        bandcamp:'',
        github:'',
        behance:'',
        dribble:'',
        portfolio:'https://beenishsarfaraz.cargo.site/',
        cv:'https://drive.google.com/file/d/1V6sgDHtljOCnWJl8vu-JxBuQFahNtzk1/view',
        shout:''
    },
    {
        id:'Tashna-Salim',
        name:'Tashna Salim',
        imgSrc:'./unnamed.jpg',
        desc:"Tashna Salim is an artist specialising in children's book illustration in a variety of traditional and digital mediums. Since 2011, she has illustrated over 100 titles, published across the globe. ",
        role:'Illustrator',
        eMail:'tashna.salim@yahoo.com',
        // phone:'+92-0900-78601',
        fb:'',
        insta:'',
        x:'',
        linkedIn:'',
        spotify:'',
        linktree:'',
        youtube:'',
        soundcloud:'',
        bandcamp:'',
        github:'',
        behance:'',
        dribble:'',
        portfolio:'https://tashnasalim.com/',
        cv:'https://www.dropbox.com/scl/fi/11agrhwrotkbumzphoatn/resume-blue.pdf?rlkey=uss8kc9ilm9ciqnl7ghqnphx5&e=1&dl=0',
        shout:''
    },
    {
        id:'rija-quadri',
        name:'Rija I. Quadri',
        imgSrc:'./rija.jpg',
        desc:"Rija is a published children's book illustrator and designer from Pakistan. She loves to connect with her clients and make their words come to life. Initially, she worked as a traditional artist but transitioned to digital art after her twins were born.  She feels it gives her a better sense of what kids would prefer to read. Moreover, it is what she would like her children to read and experience.\n\nRija claims her journey in art and motherhood has been phenomenal, even with its ups and downs. It teaches her something new, every day. She plans to make her own author- illustrator debut in the near future, with a focus on picture and coloring books.",
        role:'Illustrator',
        eMail:'riquadri@hotmail.com',
        // phone:'+92-0900-78601',
        fb:'',
        insta:'',
        x:'',
        linkedIn:'',
        spotify:'',
        linktree:'',
        youtube:'',
        soundcloud:'',
        bandcamp:'',
        github:'',
        behance:'',
        dribble:'',
        portfolio:'https://linkr.bio/rquadri06',
        cv:'https://drive.google.com/file/d/1ClrT2tQsfdhQZTsOlEhbIlCaFlFBupp1/view',
        shout:''
    },
    {
        id:'batool-yazdani',
        name:'Batool Yazdani',
        imgSrc:'./Batool.jpg',
        desc:"Batool is an independent filmmaker and editor from Karachi, Pakistan. She completed her graduate degree in filmmaking from the National College of Arts, in Lahore, Pakistan.\n\nShe has worked with multiple filmmakers, as an assistant director and has directed and edited two documentaries and two fiction films.\n\nAs an editor, she believes every project requires a different style, based on its themes and vision. An editor is like a second director to any project or film. Her effort is always to give shape and structure to the intended vision, while utilising what has already been captured on film. A good edit is when the editing is the least noticeable aspect of filmmaking. \n\nHer experience in direction allows her to understand someone else’s vision better as an editor  and how to best translate that through the edit.",
        role:'Independent Filmmaker and Editor',
        eMail:' yazdanibatool@gmail.com',
        // phone:'+92-0900-78601',
        fb:'',
        insta:'',
        x:'',
        linkedIn:'',
        spotify:'',
        linktree:'',
        youtube:'',
        soundcloud:'',
        bandcamp:'',
        github:'',
        behance:'',
        dribble:'',
        portfolio:'https://www.behance.net/batoolyazdani',
        cv:'https://drive.google.com/file/d/1ClrT2tQsfdhQZTsOlEhbIlCaFlFBupp1/view',
        shout:''
    },
    
]